services:
  service-backend:
    container_name: eventhive-docker
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 8080:8080
  postgres-event-hive-container:
    image: postgres:alpine
    restart: always
    networks:
      - pg_default
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - event-hive-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-event-hive
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  event-hive-data:

networks:
  pg_default:
    driver: bridge